### ISSUE TITLE
find_alt3prime_5prime_ss.py

### ISSUE THREAD

**Issue by dorothyzh** [BrooksLabUCSC/flair#12]
Hi for the script "find_alt3prime_5prime_ss.py", you mentioned the "colnum" argument refers to "the 0-indexed column number of the two extra columns (assumed to be last two)", I am confused about this, shall I use one column or two columns in this argument? I've tried to use command like: 
python flair/bin/find_alt3prime_5prime_ss.py output.psl 21 alt_acceptor.txt alt_donor.txt 
##
Traceback (most recent call last):
  File "flair/bin/find_alt3prime_5prime_ss.py", line 106, in <module>
    alljuncs = pslreader(psl)
  File "flair/bin/find_alt3prime_5prime_ss.py", line 25, in pslreader
    count0, count1 = int(line[colnum]), int(line[colnum + 1])
ValueError: invalid literal for int() with base 10: '27.0'

python flair/bin/find_alt3prime_5prime_ss.py output.psl 21,22 alt_acceptor.txt alt_donor.txt 

Neither of them work from the beginning line of output.psl. Not sure what is going on. 

The first line of my output.psl file is shown as below:
0       0       0       0       0       0       0       0       +       6753031f-f907-46de-933b-83191c940b72;0_1:5481000        484     0       484     1
       30427671        5481659 5482143 1       484,    0,      5481659,        27.0    4.0

Thanks

**Comment by belgravia** [comment]
Your command is fine and your psl is in the format that the script is expecting, which is good. However my script was expecting integers for counts when float counts were given. The quantification format had changed and I hadn't changed `find_alt3prime_5prime_ss.py` to match. I just pushed a newer version of the script that should fix this. Let me know how this goes!
-Alison

**Comment by dorothyzh** [comment]
Traceback (most recent call last):
  File "flair/flair/bin/find_alt3prime_5prime_ss.py", line 106, in <module>
    alljuncs = pslreader(psl)
  File "flair/flair/bin/find_alt3prime_5prime_ss.py", line 25, in pslreader
    count0, count1 = float(line[colnum]), float(line[colnum + 1])
IndexError: list index out of range

**Comment by belgravia** [comment]
I pushed an updated version of the script that takes the command line arguments as such:
`python find_alt3prime_5prime_ss.py isoforms_counts.psl 21 22 accept.txt donor.txt`
since I realize the way it read the column numbers in before was confusing. Let me know if that works for you. Thanks for your patience!
-Alison

**Comment by dorothyzh** [comment]
Sorry to bother you, I still find errors, I give you the output.psl file I used


[output.psl.txt](https://github.com/BrooksLabUCSC/flair/files/3038278/output.psl.txt)
python flair/bin/find_alt3prime_5prime_ss.py output.psl2 22 23 alt_acceptor.txt alt_donor.txt 
Traceback (most recent call last):
  File "flair/bin/find_alt3prime_5prime_ss.py", line 107, in <module>
    alljuncs = pslreader(psl)
  File "flair/bin/find_alt3prime_5prime_ss.py", line 26, in pslreader
    count0, count1 = float(line[colnum1]), float(line[colnum2])
IndexError: list index out of range

python flair/bin/find_alt3prime_5prime_ss.py output.psl2 22 22 alt_acceptor.txt alt_donor.txt 
Traceback (most recent call last):
  File "flair/bin/find_alt3prime_5prime_ss.py", line 107, in <module>
    alljuncs = pslreader(psl)
  File "flair/bin/find_alt3prime_5prime_ss.py", line 33, in pslreader
    for j in junctions:
TypeError: 'NoneType' object is not iterable

**Comment by dorothyzh** [comment]
That's my original file, I have changed the last columns of it to integer using R, but still cannot work. Thanks.
